import type { PromptLibrary, Tag, Subcategory, Category } from './types';

let counter = 0;
const id = (prefix: string) => `${prefix}-${++counter}`;

const tag = (label: string, labelRu: string, value: string): Tag => ({
  id: id('t'),
  label,
  labelRu,
  value,
});

const sub = (name: string, nameRu: string, tags: Tag[]): Subcategory => ({
  id: id('s'),
  name,
  nameRu,
  tags,
});

const cat = (name: string, nameRu: string, subcategories: Subcategory[]): Category => ({
  id: id('c'),
  name,
  nameRu,
  subcategories,
});

export function buildSeedLibrary(): PromptLibrary {
  return {
    categories: [
      cat('Anime girls', 'Аниме (девушки)', [
        sub('Konosuba', 'Konosuba', [
          tag('Aqua', 'Аква', 'aqua \\(konosuba\\), blue hair, blue eyes, long hair, hair ornament'),
          tag('Megumin', 'Мегумин', 'megumin, brown hair, red eyes, eyepatch, witch hat'),
          tag('Darkness', 'Даркнесс', 'darkness \\(konosuba\\), blonde hair, blue eyes, ponytail, armor'),
          tag('Yunyun', 'Юнъюн', 'yunyun \\(konosuba\\), black hair, red eyes, twintails'),
          tag('Wiz', 'Виз', 'wiz \\(konosuba\\), brown hair, brown eyes, witch hat'),
          tag('Eris', 'Эрис', 'eris \\(konosuba\\), silver hair, blue eyes, scar on cheek'),
          tag('Chris', 'Крис', 'chris \\(konosuba\\), silver hair, blue eyes, ponytail'),
        ]),
        sub('Re:Zero', 'Re:Zero', [
          tag('Rem', 'Рем', 'rem \\(re:zero\\), blue hair, blue eyes, maid, hair ribbon'),
          tag('Ram', 'Рам', 'ram \\(re:zero\\), pink hair, red eyes, maid, hair ribbon'),
          tag('Emilia', 'Эмилия', 'emilia \\(re:zero\\), silver hair, purple eyes, hair flower, half-elf'),
          tag('Beatrice', 'Беатрис', 'beatrice \\(re:zero\\), blonde drill hair, blue eyes, dress'),
          tag('Echidna', 'Эхидна', 'echidna \\(re:zero\\), white hair, black eyes, white dress'),
        ]),
        sub('Frieren', 'Фрирен', [
          tag('Frieren', 'Фрирен', 'frieren, white hair, green eyes, twin braids, elf, long ears'),
          tag('Fern', 'Ферн', 'fern \\(sousou no frieren\\), purple hair, brown eyes'),
          tag('Serie', 'Сериэ', 'serie \\(sousou no frieren\\), white hair, blue eyes, elf'),
        ]),
        sub('Spy x Family', 'Spy x Family', [
          tag('Yor Forger', 'Йор Форджер', 'yor briar, black hair, red eyes, hair band, long hair'),
          tag('Anya Forger', 'Аня Форджер', 'anya forger, pink hair, green eyes, short hair, child'),
          tag('Fiona Frost', 'Фиона Фрост', 'fiona frost, blonde hair, blue eyes, glasses'),
        ]),
        sub('Sword Art Online', 'Sword Art Online', [
          tag('Asuna', 'Асуна', 'asuna \\(sao\\), orange hair, brown eyes, long hair'),
          tag('Sinon', 'Сино', 'asada shino, blue hair, blue eyes, short hair'),
          tag('Suguha', 'Сугуха', 'kirigaya suguha, black hair, brown eyes'),
          tag('Alice', 'Алиса', 'alice zuberg, blonde hair, blue eyes, knight'),
        ]),
        sub('Chainsaw Man', 'Chainsaw Man', [
          tag('Power', 'Пауэр', 'power \\(chainsaw man\\), blonde hair, yellow eyes, horns, sharp teeth'),
          tag('Makima', 'Макима', 'makima \\(chainsaw man\\), red hair, ringed eyes, braid'),
          tag('Reze', 'Резе', 'reze \\(chainsaw man\\), black hair, brown eyes, ponytail'),
          tag('Quanxi', 'Цюаньси', 'quanxi \\(chainsaw man\\), white hair, eyepatch, long hair'),
        ]),
        sub('Demon Slayer', 'Клинок, рассекающий демонов', [
          tag('Nezuko', 'Незуко', 'kamado nezuko, black pink hair, pink eyes, bamboo gag'),
          tag('Mitsuri', 'Мицури', 'kanroji mitsuri, pink green hair, green eyes, hashira'),
          tag('Shinobu', 'Шинобу', 'kochou shinobu, black purple hair, butterfly hairpin'),
          tag('Kanao', 'Канао', 'tsuyuri kanao, black hair, purple eyes, butterfly hairpin'),
          tag('Daki', 'Даки', 'daki \\(kimetsu no yaiba\\), white hair, hair ornament, oiran'),
        ]),
        sub('Jujutsu Kaisen', 'Магическая битва', [
          tag('Nobara', 'Нобара', 'kugisaki nobara, orange hair, brown eyes'),
          tag('Maki', 'Маки', 'zenin maki, black hair, green eyes, glasses'),
          tag('Kasumi', 'Касуми', 'miwa kasumi, white hair, blue eyes'),
          tag('Mei Mei', 'Мэй Мэй', 'mei mei \\(jujutsu kaisen\\), silver hair'),
        ]),
        sub('Attack on Titan', 'Атака титанов', [
          tag('Mikasa', 'Микаса', 'mikasa ackerman, black hair, grey eyes, scarf, military uniform'),
          tag('Annie', 'Энни', 'annie leonhart, blonde hair, blue eyes, hood'),
          tag('Historia', 'Хистория', 'historia reiss, blonde hair, blue eyes, military uniform'),
          tag('Sasha', 'Саша', 'sasha braus, brown hair, brown eyes, ponytail'),
        ]),
        sub('My Hero Academia', 'Моя геройская академия', [
          tag('Ochako', 'Очако', 'uraraka ochako, brown hair, brown eyes, hero costume'),
          tag('Momo', 'Момо', 'yaoyorozu momo, black hair, ponytail, leotard'),
          tag('Tsuyu', 'Цую', 'asui tsuyu, green hair, large mouth'),
          tag('Mt. Lady', 'Маунт Леди', 'mt. lady, blonde hair, purple eyes, bodysuit'),
        ]),
        sub('Bleach', 'Блич', [
          tag('Rukia', 'Рукия', 'kuchiki rukia, black hair, purple eyes, shinigami'),
          tag('Orihime', 'Орихиме', 'inoue orihime, orange hair, grey eyes, hair clips'),
          tag('Yoruichi', 'Йоруичи', 'shihouin yoruichi, dark skin, purple hair, golden eyes'),
          tag('Nelliel', 'Нелл', 'nelliel tu odelschwanck, green hair, hazel eyes, mask fragment'),
        ]),
        sub('Naruto', 'Наруто', [
          tag('Hinata', 'Хината', 'hyuuga hinata, dark blue hair, white eyes, byakugan'),
          tag('Sakura', 'Сакура', 'haruno sakura, pink hair, green eyes, headband'),
          tag('Tsunade', 'Цунадэ', 'senju tsunade, blonde hair, hazel eyes, large breasts'),
          tag('Temari', 'Темари', 'temari \\(naruto\\), blonde hair, four ponytails, fan'),
          tag('Ino', 'Ино', 'yamanaka ino, blonde hair, ponytail, blue eyes'),
        ]),
        sub('Evangelion', 'Евангелион', [
          tag('Rei Ayanami', 'Рей Аянами', 'ayanami rei, blue hair, red eyes, plugsuit'),
          tag('Asuka', 'Аска', 'souryuu asuka langley, red hair, blue eyes, plugsuit, twin tails'),
          tag('Mari', 'Мари', 'makinami mari illustrious, brown hair, glasses, plugsuit'),
        ]),
        sub('Bocchi the Rock', 'Bocchi the Rock', [
          tag('Bocchi', 'Боччи', 'gotou hitori, pink hair, blue eyes, pink tracksuit, long hair'),
          tag('Kita', 'Кита', 'ikuyo kita, red hair, hazel eyes'),
          tag('Ryo', 'Рё', 'yamada ryo, blue hair, yellow eyes'),
          tag('Nijika', 'Нидзика', 'ijichi nijika, blonde hair, side ponytail'),
        ]),
        sub('Madoka Magica', 'Мадока Магика', [
          tag('Madoka', 'Мадока', 'kaname madoka, pink hair, twin tails, magical girl'),
          tag('Homura', 'Хомура', 'akemi homura, black hair, purple eyes, magical girl'),
          tag('Mami', 'Мами', 'tomoe mami, blonde hair, twin drills, magical girl'),
          tag('Sayaka', 'Саяка', 'miki sayaka, blue hair, blue eyes, magical girl'),
          tag('Kyoko', 'Кёко', 'sakura kyouko, red hair, ponytail, spear'),
        ]),
        sub('Oshi no Ko', 'Oshi no Ko', [
          tag('Ai Hoshino', 'Ай Хосино', 'hoshino ai, pink purple hair, star eyes, idol'),
          tag('Akane', 'Акане', 'kurokawa akane \\(oshi no ko\\), black hair, brown eyes'),
          tag('Kana', 'Кана', 'arima kana, red hair, twin tails, child actor'),
          tag('Ruby', 'Руби', 'hoshino ruby, pink hair, star eyes, twin tails'),
          tag('MEM-cho', 'МЕМ-чо', 'mem-cho \\(oshi no ko\\), blonde hair, hair ornaments'),
        ]),
        sub('Lycoris Recoil', 'Lycoris Recoil', [
          tag('Chisato', 'Тисато', 'nishikigi chisato, blonde hair, red eyes, hair ribbon'),
          tag('Takina', 'Такина', 'inoue takina, black hair, purple eyes, long hair'),
          tag('Mizuki', 'Мидзуки', 'nakahara mizuki, brown hair, glasses'),
        ]),
        sub('Kaguya-sama', 'Кагуя-сама', [
          tag('Kaguya', 'Кагуя', 'shinomiya kaguya, black hair, red eyes, school uniform'),
          tag('Chika', 'Тика', 'fujiwara chika, pink hair, hair ribbon, school uniform'),
          tag('Iino', 'Иино', 'iino miko, brown hair, twin tails'),
        ]),
        sub('Vocaloid / Idols', 'Вокалоид / Айдолы', [
          tag('Hatsune Miku', 'Хацунэ Мику', 'hatsune miku, twin tails, teal hair, vocaloid, headphones'),
          tag('Megurine Luka', 'Мегуринэ Лука', 'megurine luka, pink hair, blue eyes, vocaloid'),
          tag('Kasane Teto', 'Касанэ Тэто', 'kasane teto, red hair, drill twintails'),
          tag('Kafu', 'Кафу', 'kafu \\(utau\\), black hair, hair flower'),
        ]),
        sub('Toilet-Bound Hanako-kun', 'Туалетный мальчик Ханако', [
          tag('Yashiro Nene', 'Яширо Нене', 'yashiro nene, blonde hair, pigtails'),
          tag('Aoi Akane', 'Акане Аои', 'akane aoi, black hair, ponytail'),
        ]),
      ]),

      cat('Game girls', 'Игры (девушки)', [
        sub('Genshin Impact', 'Genshin Impact', [
          tag('Hu Tao', 'Ху Тао', 'hu tao \\(genshin impact\\), brown hair, red eyes, twin braids, flower'),
          tag('Raiden Shogun', 'Райдэн Сёгун', 'raiden shogun, purple hair, purple eyes, ponytail, japanese clothes'),
          tag('Ganyu', 'Гань Юй', 'ganyu \\(genshin impact\\), blue hair, gold eyes, horns, ahoge'),
          tag('Yae Miko', 'Яэ Мико', 'yae miko, pink hair, purple eyes, fox ears, miko'),
          tag('Mona', 'Мона', 'mona \\(genshin impact\\), purple hair, twin tails, leotard'),
          tag('Keqing', 'Кэ Цин', 'keqing \\(genshin impact\\), purple hair, purple eyes, twin tails'),
          tag('Lumine', 'Люмин', 'lumine \\(genshin impact\\), blonde hair, gold eyes, traveler'),
          tag('Eula', 'Эола', 'eula \\(genshin impact\\), white hair, blue eyes'),
          tag('Yelan', 'Е Лань', 'yelan \\(genshin impact\\), black hair, blue eyes, mole'),
          tag('Nilou', 'Нилу', 'nilou \\(genshin impact\\), red hair, blue eyes, dancer'),
        ]),
        sub('Honkai: Star Rail', 'Honkai: Star Rail', [
          tag('Kafka', 'Кафка', 'kafka \\(honkai: star rail\\), purple hair, purple eyes, sunglasses'),
          tag('Bronya', 'Бронька', 'bronya zaychik, white hair, blue eyes, ponytail'),
          tag('Silver Wolf', 'Сильвер Вульф', 'silver wolf \\(honkai: star rail\\), grey hair, green eyes, gamer'),
          tag('Seele', 'Зеле', 'seele \\(honkai: star rail\\), blue hair, purple eyes'),
          tag('Firefly', 'Фаерфлай', 'firefly \\(honkai: star rail\\), red hair, yellow eyes'),
          tag('Acheron', 'Ахерон', 'acheron \\(honkai: star rail\\), white black hair, red eyes, hime cut'),
        ]),
        sub('NieR: Automata', 'NieR: Automata', [
          tag('2B', '2B', '2b \\(nier:automata\\), white hair, blue eyes, blindfold, black dress'),
          tag('A2', 'A2', 'a2 \\(nier:automata\\), white hair, blue eyes, ponytail'),
          tag('Pascal', 'Паскаль', 'operator 6o \\(nier:automata\\), white hair'),
        ]),
        sub('Stellar Blade', 'Stellar Blade', [
          tag('Eve', 'Ева', 'eve \\(stellar blade\\), black hair, blue eyes, ponytail, bodysuit'),
        ]),
        sub('Resident Evil', 'Resident Evil', [
          tag('Ada Wong', 'Ада Вонг', 'ada wong, black hair, brown eyes, red dress'),
          tag('Jill Valentine', 'Джилл Валентайн', 'jill valentine, brown hair, blue eyes'),
          tag('Claire Redfield', 'Клэр Редфилд', 'claire redfield, red hair, blue eyes'),
          tag('Lady Dimitrescu', 'Леди Димитреску', 'lady dimitrescu, black hair, hat, very tall, white dress'),
        ]),
        sub('Overwatch', 'Overwatch', [
          tag('D.Va', 'D.Va', 'd.va \\(overwatch\\), brown hair, brown eyes, bodysuit, headphones'),
          tag('Tracer', 'Трейсер', 'tracer \\(overwatch\\), brown hair, brown eyes, goggles, freckles'),
          tag('Widowmaker', 'Виджоумейкер', 'widowmaker \\(overwatch\\), purple skin, ponytail, bodysuit'),
          tag('Mercy', 'Мерси', 'mercy \\(overwatch\\), blonde hair, blue eyes, halo, wings'),
          tag('Sombra', 'Сомбра', 'sombra \\(overwatch\\), black purple hair'),
        ]),
        sub('Persona 5', 'Persona 5', [
          tag('Ann', 'Энн', 'takamaki ann, blonde hair, blue eyes, twin tails, school uniform'),
          tag('Makoto', 'Макото', 'niijima makoto, brown hair, red eyes, school uniform'),
          tag('Futaba', 'Футаба', 'sakura futaba, orange hair, headphones, glasses'),
          tag('Haru', 'Хару', 'okumura haru, brown hair, brown eyes, school uniform'),
          tag('Kasumi', 'Касуми', 'yoshizawa kasumi, red hair, ponytail, ribbon'),
        ]),
        sub('Final Fantasy', 'Final Fantasy', [
          tag('Tifa', 'Тифа', 'tifa lockhart, black hair, brown eyes, white tank top, fingerless gloves'),
          tag('Aerith', 'Айрис', 'aerith gainsborough, brown hair, green eyes, pink dress, ribbon'),
          tag('Yuna', 'Юна', 'yuna \\(ff10\\), brown hair, heterochromia, summoner'),
          tag('Lulu', 'Лулу', 'lulu \\(ff10\\), black hair, red eyes, black dress'),
        ]),
        sub('Tekken / MK', 'Tekken / MK', [
          tag('Kazumi', 'Казуми', 'kazumi mishima, black hair, white kimono'),
          tag('Lili', 'Лили', 'emilie de rochefort, blonde hair, twin drills'),
          tag('Mileena', 'Милина', 'mileena \\(mortal kombat\\), black hair, sharp teeth, ninja outfit'),
          tag('Kitana', 'Китана', 'kitana \\(mortal kombat\\), black hair, ninja, fan'),
        ]),
        sub('Cyberpunk / Mass Effect', 'Cyberpunk / Mass Effect', [
          tag('Lucy', 'Люси', 'lucy \\(cyberpunk\\), white hair, red eyes, jacket, transparent jacket'),
          tag('Rebecca', 'Ребекка', 'rebecca \\(cyberpunk\\), white hair, twin tails, twin pigtails'),
          tag('Liara', 'Лиара', 'liara t soni, blue skin, asari, blue eyes'),
          tag('Tali', 'Тали', 'tali zorah, quarian, helmet, hood'),
        ]),
        sub('Witcher / Skyrim', 'Witcher / Skyrim', [
          tag('Yennefer', 'Йеннифэр', 'yennefer of vengerberg, black hair, violet eyes'),
          tag('Triss', 'Трисс', 'triss merigold, red hair, blue eyes'),
          tag('Ciri', 'Цири', 'cirilla fiona elen riannon, ashen hair, green eyes, scar'),
          tag('Serana', 'Серана', 'serana \\(skyrim\\), pale skin, vampire, hood'),
          tag('Aela', 'Аэла', 'aela the huntress, red hair, war paint'),
        ]),
        sub('League of Legends', 'League of Legends', [
          tag('Ahri', 'Ари', 'ahri \\(league of legends\\), nine tails, fox ears, white black hair'),
          tag('Jinx', 'Джинкс', 'jinx \\(league of legends\\), blue hair, twin braids, freckles'),
          tag('Vi', 'Вай', 'vi \\(league of legends\\), pink hair, undercut, gauntlets'),
          tag('Caitlyn', 'Кейтлин', 'caitlyn \\(league of legends\\), purple hair, top hat'),
          tag('Akali', 'Акали', 'akali, black hair, mask, ninja'),
        ]),
        sub('Apex / Valorant', 'Apex / Valorant', [
          tag('Wraith', 'Рейф', 'wraith \\(apex legends\\), white black hair, hood, ponytail'),
          tag('Loba', 'Лоба', 'loba andrade, black hair, ponytail, jewelry'),
          tag('Jett', 'Джетт', 'jett \\(valorant\\), white hair, ponytail, scarf'),
          tag('Sage', 'Сейдж', 'sage \\(valorant\\), green hair, robe'),
          tag('Reyna', 'Рейна', 'reyna \\(valorant\\), black hair, eye patch'),
        ]),
        sub('Tomb Raider', 'Tomb Raider', [
          tag('Lara Croft', 'Лара Крофт', 'lara croft, brown hair, ponytail, tank top, dual pistols'),
        ]),
        sub('Bayonetta / DMC', 'Bayonetta / DMC', [
          tag('Bayonetta', 'Байонетта', 'bayonetta, black hair, glasses, mole'),
          tag('Lady', 'Леди', 'lady \\(devil may cry\\), black hair, heterochromia'),
          tag('Trish', 'Триш', 'trish \\(devil may cry\\), blonde hair, green eyes'),
        ]),
        sub('Dead or Alive / SoulCalibur', 'Dead or Alive / SoulCalibur', [
          tag('Kasumi', 'Касуми', 'kasumi \\(doa\\), blonde hair, headband'),
          tag('Marie Rose', 'Мари Роуз', 'marie rose \\(doa\\), blonde hair, twin braids, gothic'),
          tag('Ivy', 'Айви', 'ivy valentine, white hair, purple eyes, large breasts'),
          tag('Taki', 'Таки', 'taki \\(soulcalibur\\), black hair, ninja'),
        ]),
        sub('Baldur\'s Gate 3', "Baldur's Gate 3", [
          tag('Shadowheart', 'Шэдоухарт', 'shadowheart \\(baldur gate\\), black hair, green eyes, half-elf'),
          tag('Karlach', 'Карлах', 'karlach \\(baldur gate\\), red skin, horns, red hair, tiefling'),
          tag('Lae\'zel', 'Лэйзель', 'lae\'zel \\(baldur gate\\), green skin, gith, ponytail'),
        ]),
      ]),

      cat('Hair', 'Волосы', [
        sub('Length', 'Длина', [
          tag('Long hair', 'Длинные', 'long hair'),
          tag('Short hair', 'Короткие', 'short hair'),
          tag('Medium hair', 'Средние', 'medium hair'),
          tag('Very long', 'Очень длинные', 'very long hair, hair past hips'),
          tag('Bob cut', 'Каре', 'bob cut'),
          tag('Pixie cut', 'Пикси', 'pixie cut'),
        ]),
        sub('Style', 'Причёска', [
          tag('Ponytail', 'Хвост', 'ponytail'),
          tag('Twin tails', 'Два хвоста', 'twin tails, twintails'),
          tag('Braid', 'Коса', 'braid, single braid'),
          tag('Twin braids', 'Две косы', 'twin braids'),
          tag('Side ponytail', 'Боковой хвост', 'side ponytail'),
          tag('Bun', 'Пучок', 'hair bun'),
          tag('Wavy hair', 'Волнистые', 'wavy hair'),
          tag('Curly hair', 'Кудрявые', 'curly hair'),
          tag('Straight hair', 'Прямые', 'straight hair'),
          tag('Messy hair', 'Растрёпанные', 'messy hair'),
          tag('Hair flower', 'Цветок в волосах', 'hair flower'),
          tag('Hair ribbon', 'Лента', 'hair ribbon'),
        ]),
        sub('Color', 'Цвет', [
          tag('Black', 'Чёрные', 'black hair'),
          tag('White', 'Белые', 'white hair'),
          tag('Silver', 'Серебристые', 'silver hair'),
          tag('Blonde', 'Блонд', 'blonde hair'),
          tag('Brown', 'Каштановые', 'brown hair'),
          tag('Red', 'Рыжие', 'red hair'),
          tag('Pink', 'Розовые', 'pink hair'),
          tag('Blue', 'Синие', 'blue hair'),
          tag('Purple', 'Фиолетовые', 'purple hair'),
          tag('Green', 'Зелёные', 'green hair'),
          tag('Multicolored', 'Многоцветные', 'multicolored hair, gradient hair'),
        ]),
      ]),

      cat('Body & Face', 'Тело и лицо', [
        sub('Body type', 'Фигура', [
          tag('Slim', 'Стройная', 'slim, slender body'),
          tag('Petite', 'Миниатюрная', 'petite, small body'),
          tag('Athletic', 'Атлетичная', 'athletic, toned body, fit'),
          tag('Curvy', 'С формами', 'curvy, hourglass figure, wide hips'),
          tag('Tall', 'Высокая', 'tall'),
          tag('Mature', 'Зрелая', 'mature female'),
        ]),
        sub('Bust', 'Грудь', [
          tag('Small breasts', 'Малая', 'small breasts'),
          tag('Medium breasts', 'Средняя', 'medium breasts'),
          tag('Large breasts', 'Большая', 'large breasts'),
          tag('Huge breasts', 'Очень большая', 'huge breasts'),
        ]),
        sub('Eyes', 'Глаза', [
          tag('Blue eyes', 'Голубые', 'blue eyes'),
          tag('Green eyes', 'Зелёные', 'green eyes'),
          tag('Red eyes', 'Красные', 'red eyes'),
          tag('Yellow eyes', 'Жёлтые', 'yellow eyes'),
          tag('Brown eyes', 'Карие', 'brown eyes'),
          tag('Purple eyes', 'Фиолетовые', 'purple eyes'),
          tag('Heterochromia', 'Гетерохромия', 'heterochromia'),
          tag('Glowing eyes', 'Светящиеся', 'glowing eyes'),
          tag('Half-closed eyes', 'Полуприкрытые', 'half-closed eyes, sleepy eyes'),
        ]),
        sub('Expression', 'Выражение', [
          tag('Smile', 'Улыбка', 'smile'),
          tag('Smirk', 'Ухмылка', 'smirk'),
          tag('Blush', 'Румянец', 'blush'),
          tag('Serious', 'Серьёзная', 'serious, neutral expression'),
          tag('Sad', 'Грустная', 'sad, frown'),
          tag('Angry', 'Злая', 'angry'),
          tag('Surprised', 'Удивлённая', 'surprised, open mouth'),
          tag('Embarrassed', 'Смущённая', 'embarrassed, blush, looking away'),
          tag('Seductive', 'Соблазнительная', 'seductive smile, half-lidded eyes'),
          tag('Pout', 'Надулась', 'pout, pouting'),
        ]),
        sub('Skin', 'Кожа', [
          tag('Fair skin', 'Светлая', 'fair skin, pale skin'),
          tag('Tanned', 'Загар', 'tanned, dark skin'),
          tag('Dark skin', 'Тёмная', 'dark skin'),
          tag('Freckles', 'Веснушки', 'freckles'),
        ]),
      ]),

      cat('Poses', 'Позы', [
        sub('Standing', 'Стоя', [
          tag('Standing', 'Стоя', 'standing, looking at viewer'),
          tag('Hands on hips', 'Руки на бёдрах', 'standing, hands on hips, confident'),
          tag('Arms crossed', 'Руки скрещены', 'arms crossed, serious'),
          tag('Hands behind back', 'Руки за спиной', 'hands behind back'),
          tag('Hands behind head', 'Руки за головой', 'hands behind head'),
          tag('Stretching', 'Потягивается', 'stretching, arms up'),
          tag('Leaning forward', 'Наклон вперёд', 'leaning forward, looking at viewer'),
          tag('Leaning on wall', 'Облокотилась', 'leaning on wall'),
          tag('Walking', 'Идёт', 'walking, dynamic pose'),
          tag('Running', 'Бежит', 'running, dynamic pose, motion blur'),
          tag('Jumping', 'Прыгает', 'jumping, mid-air'),
          tag('Dancing', 'Танцует', 'dancing, dynamic pose'),
          tag('Tip-toes', 'На цыпочках', 'tip-toes, standing'),
          tag('Holding object', 'Что-то в руках', 'holding object, looking at viewer'),
          tag('Waving', 'Машет рукой', 'waving, smile'),
          tag('Pointing', 'Показывает пальцем', 'pointing, looking at viewer'),
          tag('Spinning', 'Кружится', 'spinning, dress flap, dynamic'),
          tag('Back to viewer', 'Спиной к зрителю', 'back to viewer'),
          tag('One foot up', 'Одна нога поднята', 'one foot up, standing'),
        ]),
        sub('Sitting / Lying', 'Сидя / лёжа', [
          tag('Sitting', 'Сидит', 'sitting, looking at viewer'),
          tag('Sitting on chair', 'На стуле', 'sitting on chair'),
          tag('Sitting on bed', 'На кровати', 'sitting on bed'),
          tag('Sitting on floor', 'На полу', 'sitting on floor'),
          tag('Sitting on grass', 'На траве', 'sitting on grass, outdoor'),
          tag('Kneeling', 'На коленях', 'kneeling, looking at viewer'),
          tag('Seiza', 'На пятках (сейдза)', 'seiza, sitting'),
          tag('Lying on back', 'Лежит на спине', 'lying on back, looking at viewer'),
          tag('Lying on side', 'Лежит на боку', 'lying on side, looking at viewer'),
          tag('Lying on stomach', 'Лежит на животе', 'lying on stomach, looking at viewer'),
          tag('Crossed legs', 'Скрестила ноги', 'crossed legs'),
          tag('Hugging knees', 'Обняла колени', 'hugging knees'),
          tag('Reading book', 'Читает книгу', 'sitting, holding book, reading'),
          tag('Drinking', 'Пьёт', 'sitting, holding cup, drinking'),
          tag('Sleeping', 'Спит', 'sleeping, eyes closed, lying'),
          tag('Yawning', 'Зевает', 'yawning, sleepy'),
          tag('Stretching cat', 'Кошачья растяжка', 'stretching, on bed, arching back'),
        ]),
        sub('Suggestive', 'Откровенные', [
          tag('Bent over', 'Наклонилась', 'bent over, looking back'),
          tag('All fours', 'На четвереньках', 'all fours, looking at viewer'),
          tag('Spread legs', 'Раздвинула ноги', 'spread legs, sitting'),
          tag('Pin-up pose', 'Пин-ап', 'pin-up pose, glamour, looking at viewer'),
          tag('Arched back', 'Прогиб', 'arched back, looking at viewer'),
          tag('Lifting skirt', 'Приподнимает юбку', 'lifting skirt'),
          tag('Hands behind back tied', 'Руки связаны за спиной', 'arms behind back, bound'),
          tag('Sitting on lap', 'Сидит на коленях', 'sitting on lap'),
          tag('Selfie pose', 'Селфи', 'selfie, taking picture'),
          tag('Bedroom eyes', 'Глаза-спальни', 'bedroom eyes, half-closed eyes, looking at viewer'),
          tag('Bunny pose', 'Поза кролика', 'bunny pose, hands up, paw pose'),
          tag('Lying invitation', 'Зовёт лёжа', 'lying on bed, beckoning, finger to mouth'),
          tag('On all fours back', 'На четвереньках со спины', 'all fours, from behind, looking back'),
          tag('Hand to lips', 'Палец у губ', 'finger to lips, looking at viewer, blush'),
          tag('Wet body', 'Мокрое тело', 'wet, water drops, glistening skin'),
          tag('Lying topless from above', 'Сверху лёжа', 'lying on back, from above, looking at viewer'),
          tag('Hand on chest', 'Рука на груди', 'hand on own chest, blush'),
          tag('Touching hair', 'Трогает волосы', 'touching own hair, looking at viewer'),
        ]),
        sub('Action', 'Боевые', [
          tag('Sword stance', 'Со мечом', 'holding sword, fighting stance'),
          tag('Gun pose', 'С пистолетом', 'aiming gun, dynamic pose'),
          tag('Two pistols', 'Два пистолета', 'dual wielding, two pistols, action'),
          tag('Drawing bow', 'Натягивает лук', 'drawing bow, archer'),
          tag('Magic cast', 'Колдует', 'casting spell, magic, glowing hands'),
          tag('Mid-fight', 'В бою', 'fighting, action shot, dynamic'),
          tag('Defensive', 'Защитная стойка', 'defensive stance, shield'),
          tag('Blade swing', 'Рубит', 'sword swing, motion lines'),
        ]),
      ]),

      cat('View & Camera', 'Ракурс и камера', [
        sub('Camera angle', 'Угол съёмки', [
          tag('From above', 'Сверху', 'from above, high angle'),
          tag('From below', 'Снизу', 'from below, low angle'),
          tag('From behind', 'Сзади', 'from behind, back view'),
          tag('From side', 'Сбоку', 'from side, profile view'),
          tag('Front view', 'Спереди', 'front view, facing viewer'),
          tag('Three-quarter view', 'Три четверти', 'three-quarter view'),
          tag('Bird\'s eye view', 'С высоты птичьего полёта', "bird's eye view, top-down"),
          tag('Worm\'s eye view', 'С земли', "worm's eye view, looking up"),
          tag('Dutch angle', 'Голландский угол', 'dutch angle, tilted camera'),
          tag('Over the shoulder', 'Через плечо', 'over the shoulder, from behind'),
          tag('POV', 'От первого лица', 'pov, first person view'),
          tag('Reflection in mirror', 'Отражение в зеркале', 'reflection, mirror, looking at viewer'),
        ]),
        sub('Framing', 'Кадрирование', [
          tag('Portrait', 'Портрет', 'portrait, close-up, head shot'),
          tag('Bust', 'По грудь', 'upper body, bust shot'),
          tag('Cowboy shot', 'По бёдра', 'cowboy shot, thigh-up'),
          tag('Full body', 'В полный рост', 'full body'),
          tag('Wide shot', 'Общий план', 'wide shot, scenic'),
          tag('Extreme close-up', 'Крупный план', 'extreme close-up, eye, face detail'),
          tag('Macro shot', 'Макро', 'macro shot, detail'),
          tag('Group shot', 'Групповой план', 'group, multiple girls'),
        ]),
        sub('Distance / Depth', 'Дистанция и фокус', [
          tag('Bokeh background', 'Боке', 'bokeh, blurry background, depth of field'),
          tag('Sharp focus', 'Резкий фокус', 'sharp focus, in focus'),
          tag('Shallow DOF', 'Малая ГРИП', 'shallow depth of field, blurred background'),
          tag('Deep focus', 'Большая ГРИП', 'deep focus, everything in focus'),
          tag('Telephoto', 'Телефото', 'telephoto, compressed background'),
          tag('Wide-angle lens', 'Широкоугольный', 'wide-angle, fisheye'),
        ]),
      ]),

      cat('Clothing', 'Одежда', [
        sub('Casual', 'Повседневная', [
          tag('T-shirt', 'Футболка', 't-shirt, jeans'),
          tag('Sundress', 'Сарафан', 'sundress, summer'),
          tag('Hoodie', 'Худи', 'hoodie, casual'),
          tag('Sweater', 'Свитер', 'sweater, long sleeves'),
          tag('Oversized sweater', 'Свитер оверсайз', 'oversized sweater, sweater dress'),
          tag('Jacket', 'Куртка', 'jacket, casual'),
          tag('Bomber', 'Бомбер', 'bomber jacket, casual'),
          tag('Leather jacket', 'Кожаная куртка', 'leather jacket, biker style'),
          tag('Skirt and blouse', 'Юбка и блузка', 'skirt, blouse'),
          tag('Long coat', 'Пальто', 'long coat'),
          tag('Trenchcoat', 'Тренч', 'trench coat, belt'),
          tag('Plaid skirt', 'Клетчатая юбка', 'plaid skirt'),
          tag('Denim jacket', 'Джинсовка', 'denim jacket'),
          tag('Denim shorts', 'Джинсовые шорты', 'denim shorts, casual'),
          tag('Turtleneck', 'Водолазка', 'turtleneck sweater'),
          tag('Crop hoodie', 'Кроп-худи', 'crop hoodie, midriff'),
          tag('Overalls', 'Комбинезон', 'overalls, denim, casual'),
          tag('Pajamas', 'Пижама', 'pajamas, sleepwear'),
          tag('Cardigan', 'Кардиган', 'cardigan, long sleeves'),
        ]),
        sub('Formal / Office', 'Деловая', [
          tag('Business suit', 'Деловой костюм', 'business suit, office lady'),
          tag('Pencil skirt', 'Юбка-карандаш', 'pencil skirt, white shirt'),
          tag('Pantsuit', 'Брючный костюм', 'pantsuit'),
          tag('Evening dress', 'Вечернее платье', 'evening dress, formal'),
          tag('Cocktail dress', 'Коктейльное платье', 'cocktail dress'),
        ]),
        sub('School / Uniform', 'Школьная', [
          tag('School uniform', 'Школьная форма', 'school uniform, pleated skirt, serafuku'),
          tag('Sailor uniform', 'Матроска', 'sailor uniform, sailor collar'),
          tag('Blazer uniform', 'Блейзер', 'blazer, school uniform, tie'),
          tag('Cheerleader', 'Чирлидерша', 'cheerleader uniform, pom poms'),
          tag('Gym uniform', 'Спортивная форма', 'gym uniform, bloomers'),
        ]),
        sub('Fantasy / Costume', 'Фэнтези', [
          tag('Plate armor', 'Пластинчатый доспех', 'plate armor, knight'),
          tag('Maid', 'Горничная', 'maid, maid headdress, apron'),
          tag('Witch', 'Ведьма', 'witch hat, witch dress, robe'),
          tag('Goth', 'Готический', 'gothic, goth, black dress'),
          tag('Kimono', 'Кимоно', 'kimono, japanese clothes'),
          tag('Hanfu', 'Ханьфу', 'hanfu, chinese clothes'),
          tag('Miko', 'Мико', 'miko, shrine maiden, white shirt, red hakama'),
          tag('Nun', 'Монахиня', 'nun, habit, rosary'),
          tag('Princess gown', 'Платье принцессы', 'princess, ball gown, tiara'),
          tag('Battle dress', 'Боевое платье', 'battle dress, armor, sword'),
        ]),
        sub('Sci-Fi / Modern', 'Sci-Fi / модерн', [
          tag('Mecha pilot suit', 'Костюм пилота меха', 'mecha pilot suit, plugsuit'),
          tag('Cyberpunk', 'Киберпанк', 'cyberpunk outfit, neon, cybernetic'),
          tag('Tactical', 'Тактический', 'tactical outfit, military, vest'),
          tag('Astronaut', 'Космонавт', 'astronaut suit, space'),
          tag('Latex bodysuit', 'Латексный костюм', 'bodysuit, latex, skintight'),
        ]),
        sub('Sport / Active', 'Спорт', [
          tag('Sportswear', 'Спортивная', 'sports bra, leggings, athletic'),
          tag('Yoga pants', 'Леггинсы', 'yoga pants, sportswear'),
          tag('Track suit', 'Спортивный костюм', 'track suit, jacket'),
          tag('Tennis', 'Теннисная', 'tennis outfit, skirt, racket'),
          tag('Boxing', 'Боксёр', 'boxing gloves, sports bra, shorts'),
          tag('Ballet', 'Балетная', 'ballet, leotard, tutu'),
        ]),
        sub('Sensual / Beach', 'Откровенная / пляжная', [
          tag('Bikini', 'Бикини', 'bikini, beach'),
          tag('Micro bikini', 'Микро бикини', 'micro bikini, side-tie bikini'),
          tag('Sling bikini', 'Слинг-бикини', 'sling bikini'),
          tag('Front-tie bikini', 'Бикини на завязках', 'front-tie bikini'),
          tag('String bikini', 'Бикини-стринги', 'string bikini, thong'),
          tag('One-piece swimsuit', 'Слитный купальник', 'one-piece swimsuit'),
          tag('Cutout swimsuit', 'Купальник с вырезами', 'cutout swimsuit'),
          tag('School swimsuit', 'Сукумидзу', 'school swimsuit, sukumizu'),
          tag('Lingerie', 'Бельё', 'lingerie, lace, bra and panties'),
          tag('Babydoll', 'Бэбидолл', 'babydoll lingerie, sheer'),
          tag('Corset', 'Корсет', 'corset, bustier'),
          tag('See-through', 'Просвечивающее', 'see-through, transparent, sheer'),
          tag('Bunny suit', 'Кролик', 'playboy bunny, leotard, bunny ears'),
          tag('Bunnysuit alt', 'Боди-кролик', 'bunny suit, fishnet stockings, white cuffs'),
          tag('Cat lingerie', 'Кошачье бельё', 'cat ears, lingerie, paw gloves'),
          tag('Maid lingerie', 'Откровенная горничная', 'sexy maid, lingerie maid'),
          tag('Garter belt', 'Подвязки', 'garter belt, stockings, thigh highs'),
          tag('Mini skirt', 'Мини-юбка', 'mini skirt, thigh highs'),
          tag('Pencil mini', 'Мини-карандаш', 'tight mini skirt, office'),
          tag('Crop top', 'Кроп-топ', 'crop top, midriff, navel'),
          tag('Tube top', 'Топ-резинка', 'tube top, strapless'),
          tag('Off-shoulder', 'Открытые плечи', 'off-shoulder top, bare shoulders'),
          tag('Cleavage', 'Декольте', 'cleavage, low neckline'),
          tag('Underboob', 'Андербуб', 'underboob, crop top'),
          tag('Sideboob', 'Сайдбуб', 'sideboob'),
          tag('Backless dress', 'Платье с открытой спиной', 'backless dress, bare back'),
          tag('Tight dress', 'Облегающее платье', 'tight dress, bodycon'),
          tag('Wet shirt', 'Мокрая рубашка', 'wet shirt, see-through, wet'),
          tag('Wet white shirt', 'Мокрая белая рубашка', 'wet white shirt, see-through, no bra'),
          tag('Towel', 'Полотенце', 'towel, naked towel'),
          tag('Bath towel', 'Банное полотенце', 'bath towel, wet hair, after bath'),
          tag('Open shirt', 'Расстёгнутая рубашка', 'open shirt, exposed underwear'),
          tag('Boyshorts', 'Шортики', 'boyshorts, panties'),
          tag('Stockings only', 'Только чулки', 'no pants, stockings, panties'),
        ]),
        sub('Cosplay', 'Косплей', [
          tag('Nurse', 'Медсестра', 'nurse uniform, white dress, nurse cap'),
          tag('Stewardess', 'Стюардесса', 'stewardess uniform, scarf'),
          tag('Police', 'Полицейская', 'police officer uniform, hat'),
          tag('Pirate', 'Пиратка', 'pirate outfit, tricorne'),
          tag('Ninja', 'Ниндзя', 'ninja outfit, mask'),
          tag('Vampire', 'Вампир', 'vampire, fangs, gothic dress'),
          tag('Angel', 'Ангел', 'angel, white wings, halo'),
          tag('Demon', 'Демон', 'demon girl, horns, tail, succubus'),
          tag('Mermaid', 'Русалка', 'mermaid, fish tail, seashell bra'),
          tag('Cyber', 'Кибердевушка', 'cyborg, robotic parts, cyber'),
        ]),
      ]),

      cat('Accessories', 'Аксессуары', [
        sub('Headwear / Eyewear', 'Голова / глаза', [
          tag('Glasses', 'Очки', 'glasses'),
          tag('Sunglasses', 'Солнечные очки', 'sunglasses'),
          tag('Headphones', 'Наушники', 'headphones'),
          tag('Cat ears', 'Кошачьи уши', 'cat ears, animal ears'),
          tag('Fox ears', 'Лисьи уши', 'fox ears, animal ears'),
          tag('Wolf ears', 'Волчьи уши', 'wolf ears, animal ears'),
          tag('Bunny ears', 'Заячьи уши', 'rabbit ears'),
          tag('Hairband', 'Ободок', 'hairband'),
          tag('Hat', 'Шляпа', 'hat'),
          tag('Beret', 'Берет', 'beret'),
          tag('Beanie', 'Шапка', 'beanie'),
          tag('Crown', 'Корона', 'crown'),
          tag('Halo', 'Нимб', 'halo'),
          tag('Horns', 'Рога', 'horns'),
        ]),
        sub('Body / Hands', 'Тело / руки', [
          tag('Choker', 'Чокер', 'choker'),
          tag('Necklace', 'Колье', 'necklace'),
          tag('Earrings', 'Серьги', 'earrings'),
          tag('Bracelet', 'Браслет', 'bracelet'),
          tag('Ring', 'Кольцо', 'ring'),
          tag('Gloves', 'Перчатки', 'gloves'),
          tag('Fingerless gloves', 'Митенки', 'fingerless gloves'),
          tag('Watch', 'Часы', 'wristwatch'),
          tag('Scarf', 'Шарф', 'scarf'),
          tag('Belt', 'Ремень', 'belt'),
          tag('Backpack', 'Рюкзак', 'backpack'),
          tag('Tail', 'Хвост', 'tail, animal tail'),
          tag('Wings', 'Крылья', 'wings, angel wings'),
          tag('Mask', 'Маска', 'mask, half mask'),
        ]),
      ]),

      cat('Background', 'Фон', [
        sub('Outdoor', 'На улице', [
          tag('Forest', 'Лес', 'forest, trees, nature, sunlight through leaves'),
          tag('Field', 'Поле', 'flower field, grass, blue sky, clouds'),
          tag('Beach', 'Пляж', 'beach, ocean, sand, palm trees, sunset'),
          tag('Mountain', 'Горы', 'mountain, peak, snow-capped, alpine'),
          tag('Desert', 'Пустыня', 'desert, sand dunes, clear sky'),
          tag('Lake', 'Озеро', 'lake, calm water, reflections'),
          tag('Garden', 'Сад', 'garden, flowers, fountain'),
          tag('Cherry blossoms', 'Сакура', 'cherry blossoms, sakura, falling petals'),
          tag('Snow', 'Снег', 'snow, snowing, winter, cold'),
          tag('Rainy street', 'Дождь', 'rain, wet street, reflections, umbrella'),
          tag('Riverside', 'У реки', 'riverside, river, summer'),
          tag('Hot spring', 'Онсэн', 'onsen, hot spring, steam'),
          tag('Bamboo grove', 'Бамбуковая роща', 'bamboo grove, japanese'),
          tag('Volcano', 'Вулкан', 'volcano, lava'),
        ]),
        sub('Indoor', 'В помещении', [
          tag('Bedroom', 'Спальня', 'bedroom, bed, soft lighting'),
          tag('Living room', 'Гостиная', 'living room, sofa, modern interior'),
          tag('Kitchen', 'Кухня', 'kitchen, countertop, cooking'),
          tag('Bathroom', 'Ванная', 'bathroom, bathtub, steam'),
          tag('Library', 'Библиотека', 'library, bookshelves, warm light'),
          tag('Cafe', 'Кафе', 'cafe, coffee, cozy'),
          tag('Classroom', 'Класс', 'classroom, desks, blackboard'),
          tag('Office', 'Офис', 'office, desk, computer'),
          tag('Gym', 'Спортзал', 'gym, equipment, sportswear'),
          tag('Bar', 'Бар', 'bar, neon, night'),
          tag('Locker room', 'Раздевалка', 'locker room, lockers'),
          tag('Hospital', 'Больница', 'hospital, white walls, sterile'),
          tag('Maid cafe', 'Мейд-кафе', 'maid cafe, fancy interior'),
          tag('Shrine', 'Храм', 'shrine, japanese architecture'),
        ]),
        sub('Urban', 'Город', [
          tag('City street', 'Улица города', 'city, street, modern buildings'),
          tag('Cyberpunk', 'Киберпанк', 'cyberpunk city, neon lights, futuristic'),
          tag('Tokyo night', 'Токио ночью', 'tokyo, neon signs, night, street'),
          tag('Rooftop', 'Крыша', 'rooftop, city view, skyline'),
          tag('Alley', 'Переулок', 'alley, narrow street, urban'),
          tag('Subway', 'Метро', 'subway, train station, underground'),
          tag('Highway', 'Хайвей', 'highway, road, motion blur'),
          tag('Skyscrapers', 'Небоскрёбы', 'skyscrapers, glass buildings'),
        ]),
        sub('Fantasy / Sci-Fi', 'Фэнтези / Sci-Fi', [
          tag('Castle', 'Замок', 'castle, medieval, stone walls'),
          tag('Tavern', 'Таверна', 'tavern, fireplace, wooden interior'),
          tag('Magical forest', 'Волшебный лес', 'magical forest, glowing, fairy lights'),
          tag('Dungeon', 'Подземелье', 'dungeon, torches, stone'),
          tag('Sky island', 'Небесный остров', 'floating island, clouds, sky'),
          tag('Underwater', 'Под водой', 'underwater, bubbles, fish'),
          tag('Spaceship', 'Космический корабль', 'spaceship interior, sci-fi'),
          tag('Space', 'Космос', 'space, stars, nebula'),
          tag('Apocalyptic', 'Постапокалипсис', 'post-apocalyptic, ruins, wasteland'),
          tag('Steampunk', 'Стимпанк', 'steampunk, brass, gears'),
        ]),
      ]),

      cat('Lighting', 'Освещение', [
        sub('Time of day', 'Время суток', [
          tag('Golden hour', 'Золотой час', 'golden hour, warm sunlight'),
          tag('Sunset', 'Закат', 'sunset, orange sky'),
          tag('Sunrise', 'Рассвет', 'sunrise, soft light'),
          tag('Night', 'Ночь', 'night, moonlight'),
          tag('Blue hour', 'Синий час', 'blue hour, twilight'),
          tag('Midday', 'Полдень', 'midday, harsh sunlight'),
        ]),
        sub('Mood', 'Настроение', [
          tag('Cinematic lighting', 'Киношный свет', 'cinematic lighting, dramatic'),
          tag('Soft lighting', 'Мягкий свет', 'soft lighting, diffused light'),
          tag('Studio lighting', 'Студийный свет', 'studio lighting, professional'),
          tag('Neon lights', 'Неон', 'neon lights, glowing'),
          tag('Candlelight', 'Свечи', 'candlelight, warm glow'),
          tag('Backlighting', 'Контровый свет', 'backlight, rim light'),
          tag('Volumetric light', 'Объёмный свет', 'volumetric lighting, god rays'),
          tag('Bioluminescent', 'Биолюминесценция', 'bioluminescent, glowing'),
          tag('Spotlight', 'Прожектор', 'spotlight, dark background'),
        ]),
      ]),

      cat('Style', 'Стиль', [
        sub('Art style', 'Стиль рисунка', [
          tag('Anime', 'Аниме', 'anime style, anime, illustration'),
          tag('Manga', 'Манга', 'manga style, black and white'),
          tag('Oil painting', 'Маслом', 'oil painting, brush strokes'),
          tag('Watercolor', 'Акварель', 'watercolor, soft colors'),
          tag('Pixel art', 'Пиксель-арт', 'pixel art'),
          tag('3D render', '3D-рендер', '3d render, octane render'),
          tag('Photorealistic', 'Фотореалистичный', 'photorealistic, realistic, raw photo'),
          tag('Sketch', 'Набросок', 'sketch, pencil drawing'),
          tag('Concept art', 'Концепт-арт', 'concept art, illustration'),
          tag('Vintage', 'Винтаж', 'vintage, retro, film grain'),
        ]),
        sub('Quality', 'Качество', [
          tag('Masterpiece', 'Шедевр', 'masterpiece, best quality'),
          tag('Highly detailed', 'Детализированный', 'highly detailed, intricate details, sharp focus'),
          tag('8k', '8k', '8k, ultra high res, ultra detailed'),
          tag('Beautiful face', 'Красивое лицо', 'beautiful detailed face, perfect face'),
          tag('Detailed eyes', 'Детальные глаза', 'detailed eyes'),
        ]),
        sub('Negative', 'Негатив', [
          tag('Common negative', 'Общий негатив', 'lowres, bad anatomy, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, jpeg artifacts, signature, watermark, blurry'),
          tag('No text', 'Без текста', 'text, signature, watermark, username'),
          tag('No deformities', 'Без деформаций', 'bad anatomy, deformed, mutated, disfigured, extra limbs, missing limbs'),
          tag('No bad face', 'Без плохого лица', 'bad face, ugly face, distorted face'),
        ]),
      ]),
    ],
  };
}
